version: "2"

linters:
  enable:
    - bodyclose # checks whether HTTP response body is closed successfully
    - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
    - exhaustive # checks exhaustiveness of enum switch statements
    - forbidigo # forbids identifiers
    - gosec # inspects source code for security problems
    - govet # reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign # detects when assignments to existing variables are not used
    - makezero # finds slice declarations with non-zero initial length
    - nilnil # checks that there is no simultaneous return of nil error and an invalid value
    - noctx # finds sending http request without context.Context
    - staticcheck # is a go vet on steroids, applying a ton of static analysis checkscodes
    - unconvert # removes unnecessary type conversions
    - unparam # reports unused function parameters
    - unused # checks for unused constants, variables, functions and types
